language: node_js
node_js:
  "10"
os: osx

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

# cache:
#   directories:
#   - node_modules
before_script:
  - npm install --save-dev electron
  - npm install electron-packager --save-dev
  - npm install electron-packager -g
  - pwd
script:
  electron-packager /Users/travis/build/tebinraouf/clinic 'Dr Tanya Clinic' --out ../ --overwrite