language: node_js
node_js:
  "10"
os: osx

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

cache:
  directories:
  - node_modules

before_script:
  - npm install electron --save-dev
  - npm install electron-packager --save-dev
  - npm install electron-packager -g
  - npm install gulp -g
  - gulp build
  
script:
  - electron-packager . 'Clinic' --out ../clinicApp

before_deploy:
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - tar -zcvf clinicApp.tar.gz ../clinicApp 

deploy:
    provider: releases
    api_key: "$GitHub_Token"
    file: ../clinicApp.tar.gz
    skip_cleanup: true